### ISSUE TITLE
Multiple files with the same name

### ISSUE THREAD

**Issue by frafra** [geopaparazzi/GSS#14]
It is possible to upload multiple files with the same name, with no way to understand which one is what (no date and no simple way to download the file from the web interface).

Should the file upload be stopped, or should the new file replace the old one? Should GSS let the user decide?

A ".new" suffix could be added at the end as an easy fix.

**Comment by moovida** [comment]
This has for now been solved by adding a timestamp to the name (so a user can upload it many many times :-) ).
